Close button added mobile menu
orcasound/orcasite pull request #295
Opened 2023-12-27 12:27 UTC by Ayush1404

I have added a flexbox as opposed to the previous one, we still have to put the position absolute so that we can let the button be at the left but as it is in a flexbox now the previous issue should be solved, can you please review and see if this is what you wanted?

2024-01-11 05:10 UTC, Ayush1404 commented
Hey can you please review my changes

2024-01-13 19:39 UTC, paulcretu commented
Follow up from PR #294 

@Ayush1404 next time please update the existing PR instead of closing and opening a new one. It's a lot easier to follow along that way. Thanks!

2024-01-14 03:57 UTC, paulcretu requested changes
> Hey can you please review my changes

We're pretty limited on dev time so we do our best to review changes. On PRs this small, if they require multiple rounds of changes and you're not planning on being a regular contributor, it's more work than it's worth.

If you want to keep up with what's currently high priority and what we're working on next, please [join our Slack](https://join.slack.com/t/orcasound/shared_invite/zt-293mdpy47-El~xXZA6YmHOWoCzB~8WpQ). 

> we still have to put the position absolute

It can definitely be done without `position: absolute`, take a look at the menu icon in this very same file ([this might also help](https://stackoverflow.com/questions/38948102/center-one-and-right-left-align-other-flexbox-element)).

2025-03-13 00:23 UTC, paulcretu commented
Solved by #790 instead

2025-03-13 00:23 UTC, closed without merging